<a href="https://colab.research.google.com/github/Saivenkat4/FML/blob/main/logistic_regression_about_finding_numbers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

This packages are imported mostly from sklearn 


The code you provided is importing the StandardScaler class from the Scikit-learn library's preprocessing module.
---



In [5]:
X, y = load_digits(return_X_y=True)


In this the starting variable should be capital("X")
or there will be an error

In [6]:
X.shape,y.shape

((1797, 64), (1797,))

In [7]:
X[10],y[10]

(array([ 0.,  0.,  1.,  9., 15., 11.,  0.,  0.,  0.,  0., 11., 16.,  8.,
        14.,  6.,  0.,  0.,  2., 16., 10.,  0.,  9.,  9.,  0.,  0.,  1.,
        16.,  4.,  0.,  8.,  8.,  0.,  0.,  4., 16.,  4.,  0.,  8.,  8.,
         0.,  0.,  1., 16.,  5.,  1., 11.,  3.,  0.,  0.,  0., 12., 12.,
        10., 10.,  0.,  0.,  0.,  0.,  1., 10., 13.,  3.,  0.,  0.]),
 0)


In machine learning, X[10] and y[10] typically refer to the 11th data point in a dataset.

X usually represents the features or inputs of the dataset, and y represents the target or output variable. The features are the variables that are used to predict the target variable, while the target variable is the variable being predicted.

In [8]:
X[0],y[0]

(array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]),
 0)

In [11]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.unique(X)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16.])

In [24]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.4,random_state=1)

or

In [16]:
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.2, random_state=0)


Standardization is the process of transforming data in a way such that the mean of each column becomes equal to zero, and the standard deviation of each column is one.

In [25]:
X_train[0],np.mean(X_train[0]),np.std(X_train[0])

(array([ 0.,  2., 13., 16.,  4.,  0.,  0.,  0.,  0., 12., 12., 12., 15.,
         0.,  0.,  0.,  0.,  5.,  2.,  7., 14.,  0.,  0.,  0.,  0.,  0.,
         3., 15., 15.,  7.,  0.,  0.,  0.,  0.,  4., 12., 12., 16.,  3.,
         0.,  0.,  0.,  0.,  0.,  0., 15.,  7.,  0.,  0.,  3., 16.,  8.,
         9., 16.,  6.,  0.,  0.,  1., 11., 12., 14.,  9.,  0.,  0.]),
 5.125,
 5.98304897188716)

64 features are available 

In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)


In the code you provided, the "fit_transform" method of the StandardScaler object is being used to normalize the features in X_train. The fit_transform method fits the scaler to the training data (X_train) and applies the transformation to the training data. 

In [27]:
X_train[0],np.mean(X_train[0]),np.std(X_train[0])

(array([ 0.        ,  1.85064698,  1.6224474 ,  0.97329055, -1.83516787,
        -1.02316058, -0.41682164, -0.13231248, -0.05765437,  3.23389739,
         0.29723   , -0.02071129,  0.99874798, -1.3713515 , -0.52526846,
        -0.13943018, -0.04311306,  0.70307236, -1.42391095, -0.02568809,
         1.12232783, -1.2731698 , -0.5464966 , -0.1202086 ,  0.        ,
        -0.79017853, -0.98509819,  1.02227835,  0.81093026, -0.08903826,
        -0.61759518, -0.04311306,  0.        , -0.68542701, -0.58911582,
         0.43629784,  0.28223324,  1.24534297,  0.04279583,  0.        ,
        -0.05490561, -0.52261725, -1.0619941 , -1.14518862, -1.23703367,
         1.18678183,  0.80972969, -0.09832176, -0.04576756,  1.25655876,
         1.49068892, -0.29910394, -0.07866162,  1.20294718,  0.45998206,
        -0.20826513, -0.03047138,  0.74164463,  1.06678348, -0.0330101 ,
         0.4471682 ,  0.38490097, -0.50337913, -0.18653013]),
 0.08483504940139101,
 0.8941347445152715)

In [28]:
#create a model and train it
model=LogisticRegression(C=0.05,multi_class='ovr',random_state=0)
model.fit(X_train,y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0)

The algorithm is called "logistic regression" because it uses a logistic function to model the probability of the target variable.

1) C=0.05: the inverse of the regularization strength. A smaller value of C indicates stronger regularization, which can help prevent overfitting. The default value is C=1.0.

2) multi_class='ovr': the strategy used to handle multi-class classification problems. The options are 'ovr' (one-vs-rest) and 'multinomial' (softmax). 'ovr' is used in this case, which trains a separate binary classification model for each class, and selects the class with the highest probability as the predicted class.

3) random_state=0: the seed used by the random number generator. This is used to ensure that the results are reproducible.

In [35]:
X_test = scaler.transform(X_test)
y_prediction=model.predict(X_test)

In [39]:
#The score method returns the mean accuracy on the given test data and labels. 
model.score(X_train, y_train)

0.9693877551020408

In [40]:
model.score(X_test,y_test)

0.12239221140472879

In [43]:
confusion_matrix(y_test,y_prediction)

array([[ 0,  0,  0,  0, 74,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0, 67,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 67,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  1, 82,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 79,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 63,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 68,  0,  2,  0,  0,  0],
       [ 0,  0,  0,  0, 71,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  1, 60,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 75,  0,  1,  0,  0,  0]])

In [45]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        74
           1       0.00      0.00      0.00        68
           2       0.00      0.00      0.00        68
           3       0.50      0.01      0.02        83
           4       0.11      1.00      0.20        79
           5       1.00      0.03      0.06        65
           6       0.67      0.03      0.05        70
           7       1.00      0.04      0.08        74
           8       0.50      0.02      0.03        62
           9       0.00      0.00      0.00        76

    accuracy                           0.12       719
   macro avg       0.38      0.11      0.04       719
weighted avg       0.37      0.12      0.05       719



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [46]:
classification_report(y_test,y_prediction)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


'              precision    recall  f1-score   support\n\n           0       0.00      0.00      0.00        74\n           1       0.00      0.00      0.00        68\n           2       0.00      0.00      0.00        68\n           3       0.50      0.01      0.02        83\n           4       0.11      1.00      0.20        79\n           5       1.00      0.03      0.06        65\n           6       0.67      0.03      0.05        70\n           7       1.00      0.04      0.08        74\n           8       0.50      0.02      0.03        62\n           9       0.00      0.00      0.00        76\n\n    accuracy                           0.12       719\n   macro avg       0.38      0.11      0.04       719\nweighted avg       0.37      0.12      0.05       719\n'